version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directories:
      - "*/**"
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      node:
        patterns:
          - "*"
