name: Frontend Server CI
on:
  push:
    branches:
      - main
    paths:
      - frontend/server/**
      - frontend/api/go/**
      - .github/workflows/ci-frontend-server.yaml
  pull_request:
    paths:
      - frontend/server/**
      - frontend/api/go/**
      - .github/workflows/ci-frontend-server.yaml
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  ci:
    uses: curioswitch/go-curiostack/.github/workflows/export-go-server-ci.yaml@3bfa7a6375a4c98dd7addce076149b6103d51271
    with:
      project_dir: frontend/server
      service: frontend-server
    secrets: inherit
