name: Repository Root CI
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - "*"
  pull_request:
    paths:
      - .github/**
      - "*"
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.work
          cache-dependency-path: build/go.sum
      - run: go run ./build lint
